### ISSUE TITLE
com.dd.test里面的类应该放到 src/test/java

### ISSUE THREAD

**Issue by wendal** [TopCoderMyDream/LuliChat#16]
maven项目的基本规范

**Comment by TopCoderMyDream** [comment]
我这写的不属于单元测试,也需要放到src/test/java里嘛? 
例如:
   我突然想知道i++打印什么东西,我就随便写了个方法加上@Test注解,如果按照规范来的话是不是也需要放到src/test/java下?

**Comment by wendal** [comment]
是的, junit的scope通常是 test, 加@Test注解的注解的代码放在src/main/java下是无法编译的

**Comment by TopCoderMyDream** [comment]
done by 蛋蛋
