### ISSUE TITLE
能不能做个NutzBoot版

### ISSUE THREAD

**Issue by wendal** [TopCoderMyDream/LuliChat#5]
开个分支也行啊

**Comment by wendal** [comment]
1个月了, 继续等等等等...

**Comment by Wizzercn** [comment]
1个月+7days了, 继续等等等等...

**Comment by wendal** [comment]
弱弱地提示一下, web.xml里面:
1. freemaker servlet, 实现一个WebServletFace类
2. SessionListener,实现一个WebEventListenerFace即可

**Comment by TopCoderMyDream** [comment]
实在抱歉,最近稍许有些忙,然后晚上也没什么时间,我尽快先写nb的然后解决其他issues......(刚刚看到这个issues更新了...)

**Comment by TopCoderMyDream** [comment]
done by 蛋蛋~ ^_^

**Comment by wendal** [comment]
赞👍
